apiVersion: v1
kind: Secret
metadata:
  name: metadata-service-secret
  namespace: iwouldargue
type: Opaque
stringData:
  CASSANDRA_USERNAME: admin
  CASSANDRA_PASSWORD: admin

  REDIS_PASSWORD: admin

  JWT_SECRET_KEY: cNwcLhs3a49ZPXb5oIVpsMzHs1qXejvErzGUMHu8ki0=

---

apiVersion: v1
kind: Secret
metadata:
  name: media-service-secret
  namespace: iwouldargue
type: Opaque
stringData:
  LIVEKIT_API_KEY: dapFusazJkR-y3rNUY8dw39R8R11wj4_8hT6oazQWsA=
  LIVEKIT_API_SECRET: wj89GNanrZvMAQ64nS-doZIESGCma8Y-U0QYFfvP6qA=

---

apiVersion: v1
kind: Secret
metadata:
  name: notification-service-secret
  namespace: iwouldargue
type: Opaque
stringData:
  REDIS_PASSWORD: admin

# ---
#
# apiVersion: v1
# kind: Secret
# metadata:
#   name: livekit-secret
#   namespace: iwouldargue
# type: Opaque
# stringData:
